services:
  opensearch-node2:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
#      - type: bind
#        source: ./opensearch/data02
      - type: volume
        source: opensearch-data2
        target: /usr/share/opensearch/data
    ports:
      - 9201:9200
      - 9601:9600
    networks:
      - opensearch-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - opensearch-node1

volumes:
  opensearch-data2:
    driver: local

